### ISSUE TITLE
Implementing a better User Interface

### ISSUE THREAD

**Issue by Mohaymin** [Mohaymin/CpEditorial#1]
The page I designed had a lot of bugs. It needs to be fixed and the design needs to be improved.
However, while working on the design, I need you all to reflect the following things your code:
-> The design should be simple
-> The design should be friendly especially for "readers"
-> The page should be responsive
-> We don't want to face copyright issues once we launch the project. So, while using a template, make sure that we don't violate the copyright rules.

**Comment by mirarifhasan** [comment]
Bugs are now fixed and copyright policy is maintained carefully.
