### ISSUE TITLE
New pages: enlist your suggestions/ideas/requirements here

### ISSUE THREAD

**Issue by Mohaymin** [Mohaymin/CpEditorial#3]
So far we have chalked to create the following pages:
- Home
- About
- Contact
- Login
- Signup
- Post Editorial

As we continue with our project, we might find the necessity of building newer pages. So, whenever you find the need of a necessary page, or you come up with an idea of a new page then you can enlist them here.

**Comment by Mohaymin** [comment]
I think we need to create **Help** and **FAQ** page. I wonder if we should update '**Contacts**' page into a 'Help' page or whether we should integrate 'Help' and 'FAQ' page or to integrate all the above three pages into a single page.
When the user would like to post an editorial, he may be confused about the writing styles and other staffs. I think it is better to keep a page that would help them with this and similar matters.

**Comment by fesabelilla** [comment]
hmm
